//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace ArtTechIVRUtils.wsElektrik {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ivrserviceSoapBinding", Namespace="http://veri.com/")]
    public partial class ElectricIvrserviceagent : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback faturaOlusturOperationCompleted;
        
        private System.Threading.SendOrPostCallback faturaHesaplaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAboneBorcOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAboneEndeksOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ElectricIvrserviceagent() {
            this.Url = global::ArtTechIVRUtils.Properties.Settings.Default.ArtTechIVRUtils_wsElektrik_ElectricIvr_serviceagent;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event faturaOlusturCompletedEventHandler faturaOlusturCompleted;
        
        /// <remarks/>
        public event faturaHesaplaCompletedEventHandler faturaHesaplaCompleted;
        
        /// <remarks/>
        public event getAboneBorcCompletedEventHandler getAboneBorcCompleted;
        
        /// <remarks/>
        public event GetAboneEndeksCompletedEventHandler GetAboneEndeksCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("/Business/SOAP/Services/ElectricIvr.serviceagent/Service1SoapEndpoint1/faturaOlus" +
            "tur", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string faturaOlustur(int tesisatNo, double endex1, double endex2, double endex3) {
            object[] results = this.Invoke("faturaOlustur", new object[] {
                        tesisatNo,
                        endex1,
                        endex2,
                        endex3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void faturaOlusturAsync(int tesisatNo, double endex1, double endex2, double endex3) {
            this.faturaOlusturAsync(tesisatNo, endex1, endex2, endex3, null);
        }
        
        /// <remarks/>
        public void faturaOlusturAsync(int tesisatNo, double endex1, double endex2, double endex3, object userState) {
            if ((this.faturaOlusturOperationCompleted == null)) {
                this.faturaOlusturOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfaturaOlusturOperationCompleted);
            }
            this.InvokeAsync("faturaOlustur", new object[] {
                        tesisatNo,
                        endex1,
                        endex2,
                        endex3}, this.faturaOlusturOperationCompleted, userState);
        }
        
        private void OnfaturaOlusturOperationCompleted(object arg) {
            if ((this.faturaOlusturCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.faturaOlusturCompleted(this, new faturaOlusturCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("/Business/SOAP/Services/ElectricIvr.serviceagent/Service1SoapEndpoint1/faturaHesa" +
            "pla", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string faturaHesapla(int tesisatNo, double endex1, double endex2, double endex3) {
            object[] results = this.Invoke("faturaHesapla", new object[] {
                        tesisatNo,
                        endex1,
                        endex2,
                        endex3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void faturaHesaplaAsync(int tesisatNo, double endex1, double endex2, double endex3) {
            this.faturaHesaplaAsync(tesisatNo, endex1, endex2, endex3, null);
        }
        
        /// <remarks/>
        public void faturaHesaplaAsync(int tesisatNo, double endex1, double endex2, double endex3, object userState) {
            if ((this.faturaHesaplaOperationCompleted == null)) {
                this.faturaHesaplaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfaturaHesaplaOperationCompleted);
            }
            this.InvokeAsync("faturaHesapla", new object[] {
                        tesisatNo,
                        endex1,
                        endex2,
                        endex3}, this.faturaHesaplaOperationCompleted, userState);
        }
        
        private void OnfaturaHesaplaOperationCompleted(object arg) {
            if ((this.faturaHesaplaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.faturaHesaplaCompleted(this, new faturaHesaplaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("/Business/SOAP/Services/ElectricIvr.serviceagent/Service1SoapEndpoint1/getAboneBo" +
            "rc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAboneBorc(int tesisatNo) {
            object[] results = this.Invoke("getAboneBorc", new object[] {
                        tesisatNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAboneBorcAsync(int tesisatNo) {
            this.getAboneBorcAsync(tesisatNo, null);
        }
        
        /// <remarks/>
        public void getAboneBorcAsync(int tesisatNo, object userState) {
            if ((this.getAboneBorcOperationCompleted == null)) {
                this.getAboneBorcOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAboneBorcOperationCompleted);
            }
            this.InvokeAsync("getAboneBorc", new object[] {
                        tesisatNo}, this.getAboneBorcOperationCompleted, userState);
        }
        
        private void OngetAboneBorcOperationCompleted(object arg) {
            if ((this.getAboneBorcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAboneBorcCompleted(this, new getAboneBorcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("/Business/SOAP/Services/ElectricIvr.serviceagent/Service1SoapEndpoint1/GetAboneEn" +
            "deks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAboneEndeks(string tesisatNo) {
            object[] results = this.Invoke("GetAboneEndeks", new object[] {
                        tesisatNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAboneEndeksAsync(string tesisatNo) {
            this.GetAboneEndeksAsync(tesisatNo, null);
        }
        
        /// <remarks/>
        public void GetAboneEndeksAsync(string tesisatNo, object userState) {
            if ((this.GetAboneEndeksOperationCompleted == null)) {
                this.GetAboneEndeksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAboneEndeksOperationCompleted);
            }
            this.InvokeAsync("GetAboneEndeks", new object[] {
                        tesisatNo}, this.GetAboneEndeksOperationCompleted, userState);
        }
        
        private void OnGetAboneEndeksOperationCompleted(object arg) {
            if ((this.GetAboneEndeksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAboneEndeksCompleted(this, new GetAboneEndeksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void faturaOlusturCompletedEventHandler(object sender, faturaOlusturCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class faturaOlusturCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal faturaOlusturCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void faturaHesaplaCompletedEventHandler(object sender, faturaHesaplaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class faturaHesaplaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal faturaHesaplaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getAboneBorcCompletedEventHandler(object sender, getAboneBorcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAboneBorcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAboneBorcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAboneEndeksCompletedEventHandler(object sender, GetAboneEndeksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAboneEndeksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAboneEndeksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591